service: opendata-berlin

provider:
  name: aws
  runtime: python2.7
  profile: prototypefund
  region: eu-central-1
  timeout: 300

package:
  include:
    - models
    - db
    - cloud
    - opendata
    - handler.py
    - requirements.txt
  exclude:
    - berlin
    - .env

functions:
  load:
    handler: handler.load_data
  import:
    handler: handler.import_package
  create_db:
    handler: handler.create_db

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
