version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-jessie
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest --cov=./
      - run: bash <(curl -s https://codecov.io/bash)
