version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-jessie
    steps:
      - checkout
      - restore_cache:
          key: v1-py-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Activate venv and install requirements
          command: |
            virtualenv ~/venv
            echo ". ~/venv/bin/activate" >> $BASH_ENV
            source $BASH_ENV
            pip install -r requirements.txt
      - save_cache:
          name: Save python deps cache
          key: v1-py-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/venv
      - run: pytest --cov=./
      - run: bash <(curl -s https://codecov.io/bash)
